### ISSUE TITLE
chainctl curl download sometimes fails.

### ISSUE THREAD

**Issue by alon-zeltser-cyera** [chainguard-dev/setup-chainctl#12]
Hello.

We encounter an issue where the action fails in the chainctl curl download due to a timeout.

```
Run chainguard-dev/setup-chainctl@main
Run cd $(mktemp -d)
Downloading chainctl from https://dl.enforce.dev/chainctl/latest/chainctl_linux_x86_64
Error: Process completed with exit code 28.
```
It is not repeatable/reproducible just a flaky timeout issue.
But when it happens our entire job/pipeline fails, and we try to eliminate such incidents that can be avoided by a simple retry.

Can you please consider adding a retry to the curl to avoid "flakiness" 
e.g https://github.com/chainguard-dev/setup-chainctl/blob/f52718d822dc73d21a04ef2082822c4a203163b3/action.yaml#L85

this can be as simple as 
```
curl -o ./${out} -fsL --retry 5 "${url}"
```
or more complicated with configurable values etc...

I can provide a PR if it helps.

Thanks

**Comment by cpanato** [comment]
released the fix in https://github.com/chainguard-dev/setup-chainctl/releases/tag/v0.2.3
